version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: canopynet_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Node.js Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: canopynet_backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Vue.js Frontend Service (UPDATED)
  # ... other services
  # Vue.js Frontend Service (CORRECTED)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canopynet_frontend
    restart: always
    ports:
      - "8080:83"
    depends_on:
      - backend
# ... other services

volumes:
  postgres_data: